### ISSUE TITLE
localhost:8765 not found (backend)

### ISSUE THREAD

**Issue by planerfolg** [david-loe/abrechnung#124]
Hallo,
ich habe localhost:8000 auf localhost:8765 geändert, und in Windows Defender 8765 frei gegeben. localhost:5000 wird gefunden, localhost:8765 jedoch nicht. In der Konsole wird 
"GET
http://localhost:8765/
[HTTP/1.1 404 Not Found 4ms]
Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource (img-src) auf http://localhost:8765/favicon.ico blockiert, da sie gegen folgende Direktive verstößt: "default-src 'none'" "

angezeigt. 
Beim Laden von localhost:5000 erhalte ich ebenfalls  folgenden Fehler in der Konsole
GET
http://localhost:8765/auth/authenticated
[HTTP/1.1 401 Unauthorized 7ms]

Was kann ich tun?
Viele Grüße

**Comment by david-loe** [comment]
Hi,
wichtig ist dass du `VITE_BACKEND_URL` entsprechend setzt wenn du den Port geändert hast und dann nochmal `docker compose up --build` ausführst.

**Comment by david-loe** [comment]
Was zeigt `docker ps` an?

Läuft der Browser mit dem du auf `localhost:5000` zugreifst auf der selben Maschine wie Docker? (Keine VM oder kein anderer PC im Netzwerk)

**Comment by david-loe** [comment]
@planerfolg 
Achso, sehe gerade dass du eine externe Mongo DB benutzt.
Vielleicht kommt daher der Fehler, Versuch's mal mit den Standard Einstellungen für die Mongo URL.

Sonst wären die Logs von `docker compose Up backend` auch interessant

**Comment by planerfolg** [comment]
> @planerfolg Achso, sehe gerade dass du eine externe Mongo DB benutzt. Vielleicht kommt daher der Fehler, Versuch's mal mit den Standard Einstellungen für die Mongo URL.
> 
> Sonst wären die Logs von `docker compose Up backend` auch interessant

Nach viel Probieren gibt es Erfolge und Misserfolge.
Was läuft: localhost:5000 kann ich bei Verwendung von der externen Mongo DB erfolgreich nutzen. Bei localhost:8765 bekomme ich immer noch den Fehler - bin aber auch nicht sicher, ob ich das backend überhaupt angezeigt brauche, weil über localhost:5000 mit admin-Rechten ja scheinbar alles zu administrieren ist. In der externen MongoDB wurde automatisch eine Database test angelegt mit diversen collections, die ich bearbeiten kann.

Eigentlich würde ich aber gerne mit einer lokalen Mongo DB arbeiten. Ich habe MongoDB Compass. Dort habe ich eine connection mit dem Namen db_connection ( connection string mongodb://localhost:27017/ ). In dieser gibt es eine database db_database und darin wieder eine collection db_collection.
Wähle ich nun als MONGO_URL=mongodb://localhost:27017/ oder MONGO_URL=mongodb://localhost:27017/db_connection oder MONGO_URL=mongodb://localhost:27017/db_database, so erhalte ich nach endlichem Warten folgenden Error:

10:28:20 PM - Starting compilation in watch mode...
frontend-1       |
frontend-1       | 
frontend-1       | 10:28:41 PM - Found 0 errors. Watching for file changes.
backend-1        | Disconnected from Database
backend-1        | /app/node_modules/mongoose/lib/connection.js:909
backend-1        |     err = new ServerSelectionError();
backend-1        |^
backend-1        |
backend-1        | MongooseServerSelectionError: connection timed out
backend-1        |     at _handleConnectionErrors (/app/node_modules/mongoose/lib/connection.js:909:11)       
backend-1        |     at NativeConnection.openUri (/app/node_modules/mongoose/lib/connection.js:860:11)      
backend-1        |     at async connectDB (file:///app/dist/app/db.js:24:9)                                   
backend-1        |     at async getSettings (file:///app/dist/app/db.js:128:5)
backend-1        |     at async file:///app/dist/app/models/travel.js:10:100 {                                
backend-1        |   reason: TopologyDescription {                                                            
backend-1        |     type: 'Unknown',                                                                       
backend-1        |     servers: Map(1) {                                                                      
backend-1        |       'localhost:27017' => ServerDescription {                                             
backend-1        |         address: 'localhost:27017',                                                        
backend-1        |         type: 'Unknown',                                                                   
backend-1        |hosts: [],                                                                         
backend-1        |         passives: [],
backend-1        |         arbiters: [],                                                                      
backend-1        |         tags: {},                                                                          
backend-1        |         minWireVersion: 0,                                                                 
backend-1        |         maxWireVersion: 0,                                                                 
backend-1        |         roundTripTime: -1,                                                                 
backend-1        |         minRoundTripTime: 0,                                                               
backend-1        |         lastUpdateTime: 23705582,                                                          
backend-1        |lastWriteDate: 0,                                                                  
backend-1        |         error: MongoNetworkTimeoutError: connection timed out
backend-1        |             at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:358:20)                                                                                                             
backend-1        |             at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:273:43)
backend-1        |             at Object.onceWrapper (node:events:638:28)                                     
backend-1        |             at Socket.emit (node:events:524:28)                                            
backend-1        |             at Socket._onTimeout (node:net:602:8)                                          
backend-1        |             at listOnTimeout (node:internal/timers:594:17)                                 
backend-1        |             at process.processTimers (node:internal/timers:529:7) {                        
backend-1        |           [Symbol(errorLabels)]: Set(2) { 'ResetPool', 'InterruptInUseConnections' },
backend-1        |           [cause]: undefined                                                               
backend-1        |         },                                                                                 
backend-1        |         topologyVersion: null,                                                             
backend-1        |         setName: null,                                                                     
backend-1        |         setVersion: null,                                                                  
backend-1        |         electionId: null,                                                                  
backend-1        |         logicalSessionTimeoutMinutes: null,                                                
backend-1        |maxMessageSizeBytes: null,                                                         
backend-1        |         maxWriteBatchSize: null,
backend-1        |         maxBsonObjectSize: null,                                                           
backend-1        |         primary: null,                                                                     
backend-1        |         me: null,                                                                          
backend-1        |         '$clusterTime': null                                                               
backend-1        |       }                                                                                    
backend-1        |     },                                                                                     
backend-1        |     stale: false,                                                                          
backend-1        |     compatible: true,
backend-1        |     heartbeatFrequencyMS: 10000,                                                           
backend-1        |     localThresholdMS: 15,                                                                  
backend-1        |     setName: null,                                                                         
backend-1        |     maxElectionId: null,                                                                   
backend-1        |     maxSetVersion: null,                                                                   
backend-1        |     commonWireVersion: 0,                                                                  
backend-1        |     logicalSessionTimeoutMinutes: null                                                     
backend-1        |   },                                                                                       
backend-1        |   code: undefined
backend-1        | }                                                                                          
backend-1        |                                                                                            
backend-1        | Node.js v22.12.0                                                                           
backend-1        | [nodemon] app crashed - waiting for file changes before starting...

**Comment by david-loe** [comment]
Also der Fehler zeigt ja, dass dein Backend Container unter der verwendeten Adresse keinen Mongo DB Server findet.

Du musst also sicherstellen dass du die richtige URL verwendest.

In der compose.yml ist doch schon ein Mongo DB Container dabei, warum benutzt du den nicht?

**Comment by planerfolg** [comment]
Danke erstmal für Deine Geduld. Ich hänge gleich das log an - ich habe nochmals gecloned, und bis auf die 2 Ports 8765 statt 8000 nichts geändert, insbesondere nicht an der MONGO_URL. Vor dem Log schicke ich die .env 

# development | production
NODE_ENV=development

# URL to reach the frontend and backend (without trailing slash)
VITE_FRONTEND_URL=http://localhost:5000
VITE_BACKEND_URL=http://localhost:8765

# Timezone - find yours here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Etc/UTC

# Cookie Secret (use something like: 'openssl rand -base64 30')
COOKIE_SECRET=<30digit>

# Magic Login (use something like: 'openssl rand -base64 60')
MAGIC_LOGIN_SECRET=<60digit>

# Ports
FRONTEND_PORT=5000
BACKEND_PORT=8765
BACKEND_DEBUG_PORT=9229
INBUCKET_UI_PORT=9000
MONGO_EXPRESS_PORT=8081

# URL of the data base
MONGO_URL=mongodb://db:27017/abrechnung

# Maximal size allowed of files being uploaded
VITE_MAX_FILE_SIZE=16000000

# Rate limiting POST requests (https://github.com/express-rate-limit/express-rate-limit)
# How long to remember requests for, in milliseconds (empty for no limit)
RATE_LIMIT_WINDOW_MS=
# How many requests to allow (empty for no limit)
RATE_LIMIT=
# TRUE | number | string (https://expressjs.com/en/guide/behind-proxies.html) use BACKEND_URL/ip to validate
TRUST_PROXY=

# ⚠️Deprecated⚠️ Use send via mail under connection settings
# If set to 'TRUE', all reports will be saved to `/reports` in the backend container. Uncomment the corresponding backend volume in `docker-compose.yml` to get reports on host maschine
BACKEND_SAVE_REPORTS_ON_DISK=FALSE

###################################


PS C:\Users\User\GitClones>git clone https://github.com/david-loe/abrechnung.git
Cloning into 'abrechnung'...
remote: Enumerating objects: 9682, done.
remote: Counting objects: 100% (2102/2102), done.
remote: Compressing objects: 100% (459/459), done.
remote: Total 9682 (delta 1786), reused 1686 (delta 1641), pack-reused 7580 (from 1)Receiving objects: 100% (9682/9682), 47.66 MiB | 4.29 MiB/s
Receiving objects: 100% (9682/9682), 50.36 MiB | 4.18 MiB/s, done.
Resolving deltas: 100% (6768/6768), done.
PS C:\Users\User\GitClones\abrechnung> docker compose up --build
[+] Building 4.6s (43/43) FINISHED                                                                                         docker:desktop-linux
 => [backend internal] load build definition from Dockerfile.development                                                                   0.1s
 => => transferring dockerfile: 533B                                                                                                       0.0s 
 => [ldap internal] load build definition from Dockerfile.development                                                                      0.1s 
 => => transferring dockerfile: 93B                                                                                                        0.0s 
 => [inbucket internal] load build definition from Dockerfile.development                                                                  0.3s 
 => => transferring dockerfile: 73B                                                                                                        0.0s 
 => [mongo-express internal] load build definition from Dockerfile.development                                                             0.2s 
 => => transferring dockerfile: 69B                                                                                                        0.0s 
 => [ldap internal] load metadata for docker.io/gitea/test-openldap:latest                                                                 1.1s
 => [frontend internal] load metadata for docker.io/library/node:22-alpine                                                                 1.6s 
 => [mongo-express internal] load metadata for docker.io/library/mongo-express:latest                                                      1.0s 
 => [inbucket internal] load metadata for docker.io/inbucket/inbucket:latest                                                               1.1s 
 => [ldap auth] gitea/test-openldap:pull token for registry-1.docker.io                                                                    0.0s 
 => [backend auth] library/node:pull token for registry-1.docker.io                                                                        0.0s 
 => [mongo-express auth] library/mongo-express:pull token for registry-1.docker.io                                                         0.0s 
 => [inbucket auth] inbucket/inbucket:pull token for registry-1.docker.io                                                                  0.0s 
 => [ldap internal] load .dockerignore                                                                                                     0.1s 
 => => transferring context: 2B                                                                                                            0.0s 
 => CACHED [ldap 1/1] FROM docker.io/gitea/test-openldap:latest@sha256:b66527e298d6062d5289dc411d1b8da1c593f8140a3d1f863e8d9d021234122f    0.1s 
 => => resolve docker.io/gitea/test-openldap:latest@sha256:b66527e298d6062d5289dc411d1b8da1c593f8140a3d1f863e8d9d021234122f                0.1s 
 => [mongo-express internal] load .dockerignore                                                                                            0.0s 
 => => transferring context: 2B                                                                                                            0.0s 
 => CACHED [mongo-express 1/1] FROM docker.io/library/mongo-express:latest@sha256:1b23d7976f0210dbec74045c209e52fbb26d29b2e873d6c6fa3d3f0  0.2s 
 => => resolve docker.io/library/mongo-express:latest@sha256:1b23d7976f0210dbec74045c209e52fbb26d29b2e873d6c6fa3d3f0ae32c2a64              0.2s 
 => [inbucket internal] load .dockerignore                                                                                                 0.0s 
 => => transferring context: 2B                                                                                                            0.0s 
 => [ldap] exporting to image                                                                                                              0.5s 
 => => exporting layers                                                                                                                    0.0s 
 => => exporting manifest sha256:23da6b9e02319f26d249efc4d67a86b65c1cd24f5120cfe80f209788d09ea89e                                          0.0s 
 => => exporting config sha256:51b24b94b4dbe8af946613482bbbdb7dea7a59c413bf536ea7a8fee9d15081af                                            0.0s 
 => => exporting attestation manifest sha256:f57d4f07acf2561e53d849cbdf2e12d31bc2bac10098ea87344fc60ad900995f                              0.1s 
 => => exporting manifest list sha256:17460fdf68fd7c6974cdb16d2f157295fccc53dd99856b8e3ca07f25b888c0c9                                     0.1s 
 => => naming to docker.io/library/abrechnung-ldap:latest                                                                                  0.0s 
 => => unpacking to docker.io/library/abrechnung-ldap:latest                                                                               0.0s 
 => CACHED [inbucket 1/1] FROM docker.io/inbucket/inbucket:latest@sha256:ad29b1e763c9803c904e17a6ba8502c4dcfa45360420fdc000b913ca4824d0f9  0.2s 
 => => resolve docker.io/inbucket/inbucket:latest@sha256:ad29b1e763c9803c904e17a6ba8502c4dcfa45360420fdc000b913ca4824d0f9                  0.2s 
 => [backend internal] load .dockerignore                                                                                                  0.0s 
 => => transferring context: 2B                                                                                                            0.0s 
 => [frontend 1/5] FROM docker.io/library/node:22-alpine@sha256:96cc8323e25c8cc6ddcb8b965e135cfd57846e8003ec0d7bcec16c5fd5f6d39f           0.2s 
 => => resolve docker.io/library/node:22-alpine@sha256:96cc8323e25c8cc6ddcb8b965e135cfd57846e8003ec0d7bcec16c5fd5f6d39f                    0.0s 
 => [backend internal] load build context                                                                                                  1.5s 
 => => transferring context: 261.61kB                                                                                                      1.3s 
 => [mongo-express] exporting to image                                                                                                     0.5s 
 => => exporting layers                                                                                                                    0.0s 
 => => exporting manifest sha256:9ce3d0ce51a76cd77951152a439ca59196d8f6fc8e156e007f356f146b841eb6                                          0.0s 
 => => exporting config sha256:28ab6be1b9c727bb6caf3d3900bb5c36d49caacf15f2e17da51c0fd6f25c480c                                            0.1s 
 => => exporting attestation manifest sha256:0256671707a4fa6a1be237c7b9f2ca383dcf757b217f2e8a1a41cbcf6709a7db                              0.2s 
 => => exporting manifest list sha256:cf8c6005368f2d4ce0258793c7a7da71dfa5cab50dadb585a5b10981ba40da95                                     0.1s 
 => => naming to docker.io/library/abrechnung-mongo-express:latest                                                                         0.0s 
 => => unpacking to docker.io/library/abrechnung-mongo-express:latest                                                                      0.0s 
 => [inbucket] exporting to image                                                                                                          0.5s 
 => => exporting layers                                                                                                                    0.0s 
 => => exporting manifest sha256:e7ae401af881b70d688475854514839964ce16307c28e9d5e7e4ebf114a84657                                          0.0s 
 => => exporting config sha256:eb4a3483c6e0f1ff3c78f39be02fc65839211de0d7ed561668c091fbff238083                                            0.1s 
 => => exporting attestation manifest sha256:495ca55e1ec48677d35da0659ac81d1805289e75f0c42057e6d6dc5747271704                              0.2s 
 => => exporting manifest list sha256:48519a2dae760b2c0d384183eded07f911debaf641183fb54d872b48ecf75c9e                                     0.0s 
 => => naming to docker.io/library/abrechnung-inbucket:latest                                                                              0.0s 
 => => unpacking to docker.io/library/abrechnung-inbucket:latest                                                                           0.0s 
 => [ldap] resolving provenance for metadata file                                                                                          0.1s 
 => [mongo-express] resolving provenance for metadata file                                                                                 0.1s 
 => [inbucket] resolving provenance for metadata file                                                                                      0.0s 
 => CACHED [backend 2/6] RUN mkdir /reports                                                                                                0.0s 
 => CACHED [backend 3/6] WORKDIR /npm_cache                                                                                                0.0s 
 => CACHED [backend 4/6] COPY backend/package*.json ./                                                                                     0.0s 
 => CACHED [backend 5/6] RUN npm install                                                                                                   0.0s 
 => CACHED [backend 6/6] WORKDIR /app                                                                                                      0.0s 
 => [backend] exporting to image                                                                                                           0.2s 
 => => exporting layers                                                                                                                    0.0s 
 => => exporting manifest sha256:7c546a455b94a84971acb8aa58ec30ac2ccd936879fc6dab683028b5e5c48b33                                          0.0s 
 => => exporting config sha256:36f550589be849cdcd8cf03083c1d205cac317a3fa2b80c8b9b13dc19dbd80f0                                            0.0s 
 => => exporting attestation manifest sha256:47e7877a3a2b5c210b042a9c9c95ad32e73eeea8cdb44cf6d937f772ce0824c3                              0.1s 
 => => exporting manifest list sha256:25691d0c57fc3855afb371a2d7b8a565ca488d71b77f39bb87440b3d9fb3053f                                     0.0s 
 => => naming to docker.io/library/abrechnung-backend:latest                                                                               0.0s 
 => => unpacking to docker.io/library/abrechnung-backend:latest                                                                            0.0s 
 => [backend] resolving provenance for metadata file                                                                                       0.0s 
 => [frontend internal] load build definition from Dockerfile.development                                                                  0.0s 
 => => transferring dockerfile: 513B                                                                                                       0.0s 
 => [frontend internal] load .dockerignore                                                                                                 0.0s 
 => => transferring context: 2B                                                                                                            0.0s 
 => [frontend internal] load build context                                                                                                 0.0s 
 => => transferring context: 175.40kB                                                                                                      0.0s 
 => CACHED [frontend 2/5] WORKDIR /npm_cache                                                                                               0.0s 
 => CACHED [frontend 3/5] COPY frontend/package*.json ./                                                                                   0.0s 
 => CACHED [frontend 4/5] RUN npm install                                                                                                  0.0s 
 => CACHED [frontend 5/5] WORKDIR /app                                                                                                     0.0s 
 => [frontend] exporting to image                                                                                                          0.2s 
 => => exporting layers                                                                                                                    0.0s 
 => => exporting manifest sha256:858d0a555f6b1efedc2ed152a1faa6231a60648734cc8465aaa09098a1145da8                                          0.0s 
 => => exporting config sha256:63455efc4743c80e1583445c1db8190da9f7c68a023d46d84323d73199fa2a57                                            0.0s
 => => exporting attestation manifest sha256:1c740a1d8f42cc8b2a692b399473736a7efedbcc2d19604f5076e0902ad35d1a                              0.1s 
 => => exporting manifest list sha256:dde4e1557da0971a0867a08643074ce73006d726157e4f4eba9af1cb01d83406                                     0.0s 
 => => naming to docker.io/library/abrechnung-frontend:latest                                                                              0.0s 
 => => unpacking to docker.io/library/abrechnung-frontend:latest                                                                           0.0s 
 => [frontend] resolving provenance for metadata file                                                                                      0.0s 
[+] Running 8/8
 ✔ Network abrechnung_defaultCreated-------------------------------------------------------------------XX0.1s 
 ✔ Volume "abrechnung_db_data"Created-------------------------------------------------------------------XX0.0s 
 ✔ Container abrechnung-db-1Created-------------------------------------------------------------------XX0.3s 
 ✔ Container abrechnung-ldap-1Created-------------------------------------------------------------------XX0.4s 
 ✔ Container abrechnung-inbucket-1       Created-------------------------------------------------------------------XX0.3s 
 ✔ Container abrechnung-backend-1        Created-------------------------------------------------------------------XX0.2s 
 ✔ Container abrechnung-mongo-express-1  Created-------------------------------------------------------------------XX0.2s 
 ✔ Container abrechnung-frontend-1       Created-------------------------------------------------------------------XX0.2s 
Attaching to backend-1, db-1, frontend-1, inbucket-1, ldap-1, mongo-express-1
inbucket-1       | Installing default greeting.html to /config
ldap-1           | starting slapd on port 389 and 636...
ldap-1           | 67533d88 @(#) $OpenLDAP: slapd  (May 23 2018 04:25:19) $                                                                     
ldap-1           | Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
ldap-1           | 67533d88 hdb_db_open: database "dc=planetexpress,dc=com": unclean shutdown detected; attempting recovery.                    
ldap-1           | 67533d88 slapd starting
mongo-express-1  | Waiting for db:27017...
mongo-express-1  | /docker-entrypoint.sh: connect: Connection refused
mongo-express-1  | /docker-entrypoint.sh: line 15: /dev/tcp/db/27017: Connection refused                                                        
mongo-express-1  | Fri Dec  6 18:08:10 UTC 2024 retrying to connect to db:27017 (2/10)                                                          
mongo-express-1  | No custom config.js found, loading config.default.js
mongo-express-1  | Welcome to mongo-express 1.0.2
mongo-express-1  | ------------------------                                                                                                     
mongo-express-1  |                                                                                                                              
mongo-express-1  | Welcome to mongo-express 1.0.2------------------------------------------------------------------XXmongo-express-1  | Welcome to mongo-express 1.0.2
mongo-express-1  | Welcome to mongo-express 1.0.2------------------------------------------------------------------XXmongo-express-1  | Welcome to mongo-express 1.0.2
mongo-express-1  | Welcome to mongo-express 1.0.2
mongo-express-1  | Welcome to mongo-express 1.0.2------------------------------------------------------------------XXmongo-express-1  | Welcome to mongo-express 1.0.2----------------------------------------------------------XXmongo-express-1  | Welcome to mongo-express 1.0.2----------------------------------------------------XXmongo-express-1  | Welcome to mongo-express 1.0.2------------------------------------------------XXmongo-express-1  | Welcome to mongo-express 1.0.2------------------------------------------------------------------XXmongo-express-1  | ------------------------------------------------------------------------------------------------XXmongo-express-1  | ------------------------------------------------------------------------------------------------XXmongo-express-1  | ------------------------------------------------------------------------------------------------XXmongo-express-1  | Mongo Express server listening at http://0.0.0.0:8081-------------------------------------------XXmongo-express-1  | Server is open to allow connections from anyone (0.0.0.0)---------------------------------------XXmongo-express-1  | Basic authentication is disabled. It is recommended to set the useBasicAuth to true in the config.js.
backend-1        | 
backend-1        | > abrechnung-backend@1.4.3 dev
backend-1        | > nodemon --ext ts,js,json,ejs,tsv --watch './**/*' --watch '../common/**/*' --ignore './dist/**/*' --exec 'yarn run tsoa spec-and-routes &&  npx tsc && node dist/app/server.js'                                
backend-1        | 
backend-1        | [nodemon] 3.1.7                                                                                
backend-1        | [nodemon] to restart at any time, enter `rs`
backend-1        | [nodemon] watching path(s): **/* ../common/**/*                                                
backend-1        | [nodemon] watching extensions: ts,js,json,ejs,tsv                                              
backend-1        | [nodemon] starting `yarn run tsoa spec-and-routes &&  npx tsc && node dist/app/server.js`      
backend-1        | yarn run v1.22.22                                                                              
backend-1        | $ /app/node_modules/.bin/tsoa spec-and-routes

[…………… wenig log fehlt hier, weil dann die console resettet wird }

6:11:12 PM - Starting compilation in watch mode...
frontend-1       |
backend-1        | Done in 45.20s.
frontend-1       | 
frontend-1       | 6:11:36 PM - Found 0 errors. Watching for file changes.
backend-1        | Disconnected from Database
backend-1        | /app/node_modules/mongoose/lib/connection.js:909
backend-1        |     err = new ServerSelectionError();
backend-1        |^
backend-1        | 
backend-1        | MongooseServerSelectionError: connection timed out                                             
backend-1        |     at _handleConnectionErrors (/app/node_modules/mongoose/lib/connection.js:909:11)           
backend-1        |     at NativeConnection.openUri (/app/node_modules/mongoose/lib/connection.js:860:11)          
backend-1        |     at async connectDB ([file:///app/dist/app/db.js:24:9](file:///dist/app/db.js:24:9))                                       
backend-1        |     at async getSettings ([file:///app/dist/app/db.js:128:5](file:///dist/app/db.js:128:5))
backend-1        |     at async [file:///app/dist/app/models/travel.js:10:100](file:///dist/app/models/travel.js:10:100) {                                    
backend-1        |   reason: TopologyDescription {                                                                
backend-1        |     type: 'Unknown',                                                                           
backend-1        |     servers: Map(1) {                                                                          
backend-1        |       'db:27017' => ServerDescription {                                                        
backend-1        |         address: 'db:27017',                                                                   
backend-1        |         type: 'Unknown',                                                                       
backend-1        |hosts: [],                                                                             
backend-1        |         passives: [],
backend-1        |         arbiters: [],                                                                          
backend-1        |         tags: {},                                                                              
backend-1        |         minWireVersion: 0,                                                                     
backend-1        |         maxWireVersion: 0,                                                                     
backend-1        |         roundTripTime: -1,                                                                     
backend-1        |         minRoundTripTime: 0,                                                                   
backend-1        |lastUpdateTime: 3052190,                                                               
backend-1        |         lastWriteDate: 0,
backend-1        |         error: MongoNetworkTimeoutError: connection timed out                                  
backend-1        |             at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:358:20)   
backend-1        |             at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:273:43)       
backend-1        |             at Object.onceWrapper (node:events:638:28)                                         
backend-1        |             at Socket.emit (node:events:524:28)                                                
backend-1        |             at Socket._onTimeout (node:net:602:8)                                              
backend-1        |             at listOnTimeout (node:internal/timers:594:17)                                     
backend-1        |             at process.processTimers (node:internal/timers:529:7) {                            
backend-1        |           [Symbol(errorLabels)]: Set(2) { 'ResetPool', 'InterruptInUseConnections' },          
backend-1        |           [cause]: undefined                                                                   
backend-1        |         },                                                                                     
backend-1        |         topologyVersion: null,                                                                 
backend-1        |         setName: null,                                                                         
backend-1        |         setVersion: null,                                                                      
backend-1        |         electionId: null,                                                                      
backend-1        |         logicalSessionTimeoutMinutes: null,                                                    
backend-1        |         maxMessageSizeBytes: null,
backend-1        |         maxWriteBatchSize: null,                                                               
backend-1        |         maxBsonObjectSize: null,                                                               
backend-1        |         primary: null,                                                                         
backend-1        |         me: null,                                                                              
backend-1        |         '$clusterTime': null                                                                   
backend-1        |       }                                                                                        
backend-1        |     },                                                                                         
backend-1        |     stale: false,
backend-1        |     compatible: true,                                                                          
backend-1        |     heartbeatFrequencyMS: 10000,                                                               
backend-1        |     localThresholdMS: 15,                                                                      
backend-1        |     setName: null,                                                                             
backend-1        |     maxElectionId: null,                                                                       
backend-1        |     maxSetVersion: null,                                                                       
backend-1        |     commonWireVersion: 0,                                                                      
backend-1        |     logicalSessionTimeoutMinutes: null                                                         
backend-1        |   },
backend-1        |   code: undefined                                                                              
backend-1        |     commonWireVersion: 0,
backend-1        |     logicalSessionTimeoutMinutes: null
backend-1        |   },
backend-1        |   code: undefined
backend-1        | }
backend-1        |
backend-1        | Node.js v22.12.0
backend-1        | [nodemon] app crashed - waiting for file changes before starting...
